### ISSUE TITLE
Unnecessary semicolon

### ISSUE THREAD

**Issue by Kyle-Ye** [MacsedProtoss/UniqueCalendarView#1]
in `./UniqueCalendarView/UniqueCalendarView/Utils/UCVUIUtil.swift` line 16 and line 17, 
there seems to be an unnecessary semicolon at the end of each line. 😂
(Lazy to commit a PR)

![截屏2020-07-17 下午9 46 41](https://user-images.githubusercontent.com/43724855/87792841-0217d080-c877-11ea-9fed-a2add5b04655.png)

**Comment by MacsedProtoss** [comment]
这个是后期分离文件导致的问题，之前在解决一些其他问题，现在我看看

**Comment by MacsedProtoss** [comment]
solved 
说起来之前这个项目是跑不起来的 为什么没人发现（笑）
